### ISSUE TITLE
The landing page is not Mobile Responsive: WIP

### ISSUE THREAD

**Issue by gauravmandall** [Gorlabscom/gorlabs#1]
Issues in apps/web*

**Comment by vishalshahh** [comment]
You can assign this task to me I can resolve this issue and make a mobile responsive landing page.

**Comment by gauravmandall** [comment]
Done, @vishalshahh!

**Comment by vishalshahh** [comment]
apps/web: landing page is now responsive 
review my pull request #2

**Comment by gauravmandall** [comment]
Thanks for your contribution, @vishalshahh.
All checks passed! 🎉
